version: '3.9'

services:
  tempo:
    image: grafana/tempo:2.7.0
    container_name: tempo
    ports:
      - "3200:3200"   # HTTP
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    command: ["-config.file=/etc/tempo.yaml"]