// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "challenge3/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IAccountRepo is an autogenerated mock type for the IAccountRepo type
type IAccountRepo struct {
	mock.Mock
}

// CreateAcc provides a mock function with given fields: ctx, acc
func (_m *IAccountRepo) CreateAcc(ctx context.Context, acc *models.Account) (*models.Account, error) {
	ret := _m.Called(ctx, acc)

	if len(ret) == 0 {
		panic("no return value specified for CreateAcc")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Account) (*models.Account, error)); ok {
		return rf(ctx, acc)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.Account) *models.Account); ok {
		r0 = rf(ctx, acc)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.Account) error); ok {
		r1 = rf(ctx, acc)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAcc provides a mock function with given fields: id
func (_m *IAccountRepo) DeleteAcc(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAcc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *IAccountRepo) GetAll() ([]models.Account, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Account, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Account); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByAccountNumber provides a mock function with given fields: ctx, accNumber
func (_m *IAccountRepo) GetByAccountNumber(ctx context.Context, accNumber string) (*models.Account, error) {
	ret := _m.Called(ctx, accNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetByAccountNumber")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Account, error)); ok {
		return rf(ctx, accNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Account); ok {
		r0 = rf(ctx, accNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *IAccountRepo) GetById(ctx context.Context, id string) (*models.Account, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Account, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Account); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAcc provides a mock function with given fields: id, accountHolder, balance
func (_m *IAccountRepo) UpdateAcc(id uuid.UUID, accountHolder string, balance int) (*models.Account, error) {
	ret := _m.Called(id, accountHolder, balance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAcc")
	}

	var r0 *models.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int) (*models.Account, error)); ok {
		return rf(id, accountHolder, balance)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, int) *models.Account); ok {
		r0 = rf(id, accountHolder, balance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, int) error); ok {
		r1 = rf(id, accountHolder, balance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIAccountRepo creates a new instance of IAccountRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIAccountRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IAccountRepo {
	mock := &IAccountRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
