// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "challenge3/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IBankRepo is an autogenerated mock type for the IBankRepo type
type IBankRepo struct {
	mock.Mock
}

// CreateBank provides a mock function with given fields: bank
func (_m *IBankRepo) CreateBank(bank *models.Bank) (*models.Bank, error) {
	ret := _m.Called(bank)

	if len(ret) == 0 {
		panic("no return value specified for CreateBank")
	}

	var r0 *models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func(*models.Bank) (*models.Bank, error)); ok {
		return rf(bank)
	}
	if rf, ok := ret.Get(0).(func(*models.Bank) *models.Bank); ok {
		r0 = rf(bank)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.Bank) error); ok {
		r1 = rf(bank)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBank provides a mock function with given fields: id
func (_m *IBankRepo) DeleteBank(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBank")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with no fields
func (_m *IBankRepo) GetAll() ([]models.Bank, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.Bank, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.Bank); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCode provides a mock function with given fields: code
func (_m *IBankRepo) GetByCode(code string) (*models.Bank, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Bank, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Bank); ok {
		r0 = rf(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *IBankRepo) GetById(ctx context.Context, id string) (*models.Bank, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Bank, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Bank); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByName provides a mock function with given fields: name
func (_m *IBankRepo) GetByName(name string) (*models.Bank, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Bank, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Bank); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBank provides a mock function with given fields: id, bankName, bankCode
func (_m *IBankRepo) UpdateBank(id uuid.UUID, bankName string, bankCode string) (*models.Bank, error) {
	ret := _m.Called(id, bankName, bankCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBank")
	}

	var r0 *models.Bank
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string) (*models.Bank, error)); ok {
		return rf(id, bankName, bankCode)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, string, string) *models.Bank); ok {
		r0 = rf(id, bankName, bankCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Bank)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, string, string) error); ok {
		r1 = rf(id, bankName, bankCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIBankRepo creates a new instance of IBankRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIBankRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *IBankRepo {
	mock := &IBankRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
