// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "challenge3/models"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ITransactionRepo is an autogenerated mock type for the ITransactionRepo type
type ITransactionRepo struct {
	mock.Mock
}

// GetHistory provides a mock function with given fields: id
func (_m *ITransactionRepo) GetHistory(id uuid.UUID) ([]models.Transaction, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]models.Transaction, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []models.Transaction); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: accFrom, accTo, amount, adminFee
func (_m *ITransactionRepo) Transfer(accFrom uuid.UUID, accTo uuid.UUID, amount int, adminFee int) (*models.Transaction, error) {
	ret := _m.Called(accFrom, accTo, amount, adminFee)

	if len(ret) == 0 {
		panic("no return value specified for Transfer")
	}

	var r0 *models.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, int, int) (*models.Transaction, error)); ok {
		return rf(accFrom, accTo, amount, adminFee)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID, int, int) *models.Transaction); ok {
		r0 = rf(accFrom, accTo, amount, adminFee)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID, uuid.UUID, int, int) error); ok {
		r1 = rf(accFrom, accTo, amount, adminFee)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewITransactionRepo creates a new instance of ITransactionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITransactionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITransactionRepo {
	mock := &ITransactionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
